version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket="soria-cloud-test"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Client=\"https://myapp.com\" TestWithPostman=\"false\""
image_repositories = []
s3_prefix = "sam-app"
